openapi: 3.0.2
info:
  title: MoldON API V1
  version: 1.0.0
  description: |-
    3D도면 바운딩 박스 추출
    - 3D도면을 업로드하여 3D도면의 바운딩박스 값을 추출하는 기능입니다.
  x-logo: 
    url: 'https://hjjeon-0.github.io/Boundbox/MoldON_logo.png'
    altText: A Logo image of MoldON
paths:
  /Boundbox:
    post:
      summary: Boundbox
      tags:
        - 3D도면 바운딩 박스 추출
      description: >-
        3D 도면 바운딩 박스 추출
      parameters: 
        - in: formData
          name: file_3d
          type: file
          description: The 3d file to upload.
      security:
        - APIKeyAuth: []
      responses:
        '200':
          description: successfully authenticated
          content:
            application/json:
              example:
                file_name: 3D_file_name
                boundBoxLX: 125.1
                boundBoxLY: 125.1
                boundBoxLZ: 125.1
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Response_Boundbox'
        '201':
          description: Undocumented
          content:
            application/json:
              example:
                error: Undocumented
                status: 201
      requestBody:
        content:
          3d_image/igs:
            schema:
              $ref: '#/components/schemas/RequestBody_file'
          application/json:
            schema:
              $ref: '#/components/schemas/RequestBody_file_name'
servers:
  - url: http://ec2-52-79-123-200.ap-northeast-2.compute.amazonaws.com:8090/v1
    description: Production server
security:
  - APIKeyAuth: []
components:
  securitySchemes:
    APIKeyAuth:
      type: apiKey
      name: x-mold-apigw-api-key
      in: header
  schemas:
    Response_Boundbox:
      description: Respresentation of all words response.
      type: object
      properties:
        result:
          $ref: '#/components/schemas/BoundboxInfo'
    BoundboxInfo:
      description: 3D 도면 바운딩 박스 추출 결과
      type: object
      properties:
        file_name:
          description: 3D file 명
          type: string
        boundBoxLX:
          description: X값 크기
          type: float
        boundBoxLY:
          description: Y값 크기
          type: float
        boundBoxLZ:
          description: Z값 크기
          type: float
    RequestBody_file_name:
      description: Request file name
      required: ["file_name"]
      type: object
      properties:
        file_name:
          type: string
    
    RequestBody_file:
      description: Invalid extension is only igs and stp.
      required: ["file_3d"]
      type: string
      properties:
        file_name:
          type: string
          format: binary